### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by jdugan6240** [caksoylar/kakoune-smooth-scroll#16]
After having a look at your repo, I couldn't help but notice that you don't have a license for kakoune-smooth-scroll. This, unfortunately, is a bit of an issue, as my understanding is the legality of using non-licensed code under copyright law is... iffy, at best: https://choosealicense.com/no-permission/#for-users. 

I believe the general assumption for non-licensed code is that, essentially, users cannot use it for any purpose without express permission from the author (and with multiple contributors, the original author starts to fall under these restrictions as well), as there are no terms and conditions dictating how the software can be used under copyright law. Now, you have given such permission on the Kakoune discourse forums, but a newer user just perusing https://kakoune.org/plugins.html looking for Kakoune plugins doesn't necessarily know that. I seriously doubt these restrictions are what you intended, so if you wouldn't mind, I think adding a license would be a good idea.

**Comment by caksoylar** [comment]
Hey there, I had at the bottom of the README that license was MIT, which I think I saw a few other plugins do like https://github.com/Delapouite/kakoune-buffers. I guess it wasn't clear enough, given this issue :) I don't mind adding a LICENSE file explicitly so I did that now, thanks for bringing it up!
