### ISSUE TITLE
Broken on Install?

### ISSUE THREAD

**Issue by enricozb** [caksoylar/kakoune-smooth-scroll#5]
Maybe I didn't configure this correctly but, I plugged this repo in my `kakrc`, 

    plug "caksoylar/kakoune-smooth-scroll"

With no additional configuration, and `:smooth-scroll-enable` results in

    Error: 1:1: 'smooth-scroll-enable' 2:5: 'smooth-scroll-disable' 3:5: 'evaluate-commands' 12:1: 'unmap' unable to parse <percent>

Looks like it's on the `printf` line inside of `smooth-scroll-disable`.

Am I doing something wrong?

**Comment by caksoylar** [comment]
I think writing `%` as `<percent>` is a relatively new Kakoune addition here https://github.com/mawww/kakoune/commit/24c51694008351cf33604f5fa06ea49c0d106487. Can you try setting the following option:
```
plug "caksoylar/kakoune-smooth-scroll" config %{
    set global scroll_keys_normal <c-f> <c-b> <c-d> <c-u> <pageup> <pagedown> ( ) m M <a-semicolon> n <a-n> N <a-N>
}
```
(I just removed `<percent>` from the default value.)

Thanks for reporting, I'll look for an alternative way to specify it for older versions. [The latest release](https://github.com/mawww/kakoune/releases/tag/v2020.08.04) should be good with the default value.

**Comment by enricozb** [comment]
Yep that fixed it. Thanks, and nice plugin.
